### ISSUE TITLE
Uncaught SecurityError: Failed to construct 'Worker': Access to the script at 'atom://diagrams/li...

### ISSUE THREAD

**Issue by andrescarbo** [francoislaberge/atom-diagrams#20]
[Enter steps to reproduce:]

1. open any .dot document

**Atom**: 1.28.0-beta0 x64
**Electron**: 2.0.0
**OS**: Mac OS X 10.13.4
**Thrown From**: [diagrams](https://github.com/francoislaberge/atom-diagrams) package 0.28.4

### Stack Trace

Uncaught SecurityError: Failed to construct 'Worker': Access to the script at 'atom://diagrams/lib/dot-worker.js' is denied by the document's Content Security Policy.

```
At /Users/acarbo/.atom/packages/diagrams/lib/diagrams.js:230

Error: Failed to construct 'Worker': Access to the script at 'atom://diagrams/lib/dot-worker.js' is denied by the document's Content Security Policy.
    at process.nextTick (/packages/diagrams/lib/diagrams.js:230:41)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
ansible-vault 0.6.15 
atom-beautify 0.32.4 
atom-drawio 1.4.3 
atom-focus-mode 1.0.0 
atom-increment 0.3.4 
atom-jinja2 0.6.0 
atom-python-run 0.9.6 
atom-terminal 0.8.0 
atom-vagrant-manager 1.0.4 
autoclose-html 0.23.0 
autocomplete-ansible 0.1.22 
autocomplete-date 0.4.0 
autocomplete-java 1.2.7 
autocomplete-json 5.5.2 
autocomplete-paths 2.12.2 
autocomplete-python 1.10.5 
autocomplete-ruby 0.2.8 
autocomplete-xml 0.9.4 
bottom-dock 0.4.4 
build 0.70.0 
build-innosetup 0.6.2 
busy 0.7.0 
busy-signal 1.4.3 
code-peek 1.4.21 
compare-files 0.8.1 
diagrams 0.28.4 
docblockr 0.13.7 
expose 0.15.0 
file-icons 2.1.20 
git-checkout 0.3.2 
git-clone 0.2.0 
git-control 0.9.0 
git-diff-details 1.4.0 
git-log 0.4.1 
git-plus 7.10.2 
git-projects 1.17.0 
git-time-machine 2.0.1 
go-debug 1.6.2 
go-plus 5.8.3 
intentions 1.1.5 
jira-issue-search 1.0.3 
jupyter-notebook 0.0.10 
kite 0.91.0 
language-ansible 0.2.2 
language-chef 2.0.1 
language-cisco 1.4.0 
language-crontab 1.0.0 
language-groovy 0.7.0 
language-groovy-cloned-from-java 0.3.0 
language-jenkinsfile 0.1.1 
language-log 1.10.1 
language-markdown 0.25.1 
language-ninja 1.1.0 
language-rspec 0.10.0 
linter 2.2.0 
linter-ansible-linting 1.3.2 
linter-ansible-syntax 1.2.0 
linter-erb 1.1.1 
linter-javac 1.9.4 
linter-manager 0.2.12 
linter-ruby-lint 1.2.0 
linter-ui-default 1.7.1 
linter-vagrant-validate 1.1.0 
markdown-preview-plus 3.1.1 
merge-conflicts 1.4.5 
monokai-slate 0.6.0 
no-title-bar 1.11.4 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
npm 2.0.0 
open-git-modified-files 0.2.4 
open-in-sourcetree 0.1.9 
open-on-bitbucket 0.5.0 
overlay-status-icons 0.1.6 
pdf-view 0.70.0 
pigments 0.40.2 
project-manager 3.3.5 
project-quick-open 0.5.0 
punchclock 0.6.5 
python-debugger 0.2.0 
release-notes 0.53.0 
royal-syntax 0.0.1 
rspec 0.4.0 
rubocop-auto-correct 1.5.1 
ruby-navigator 0.5.0 
ruby-syntax-replacer 0.5.1 
script 3.18.0 
seti-super-compact-ui 1.9.9 
seti-ui 1.10.0 
seti-ui-beta 0.1.1 
slack-chat 3.4.2 
split-diff 1.5.2 
ssh-config 0.13.0 
term3 0.22.1 
todo-manager 0.2.10 
tree-view-git-branch 0.1.2 
tree-view-git-status 1.5.0 
vim-mode-plus 1.32.0 
Zen 0.18.0 
```

Thanks

**Comment by duchonic** [comment]
Same problem

**Comment by Francois-Laberge-Bose** [comment]
Hey guys. Sorry, just too busy these days to fix this. Sorry!

**Comment by Francois-Laberge-Bose** [comment]
Fixed in https://github.com/francoislaberge/atom-diagrams/pull/22. New version is published to atom.io/package.

**Comment by duchonic** [comment]
Thank you, works fine
