### ISSUE TITLE
Failed to load the diagrams package

### ISSUE THREAD

**Issue by rantoniuk** [francoislaberge/atom-diagrams#24]
**Atom**: 1.37.0 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.5
**Thrown From**: [diagrams](https://github.com/francoislaberge/atom-diagrams) package 0.30.0

### Stack Trace

Failed to load the diagrams package

```
At Cannot find module 'space-pen'

Error: Cannot find module 'space-pen'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:154765)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146072)
    at /packages/diagrams/lib/svg-view.coffee:1:10)
    at /packages/diagrams/lib/svg-view.coffee:1:1)
    at /packages/diagrams/lib/svg-view.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146782)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146072)
    at /packages/diagrams/lib/svg-previewer.coffee:1:11)
    at /packages/diagrams/lib/svg-previewer.coffee:1:1)
    at /packages/diagrams/lib/svg-previewer.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146782)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146072)
    at /packages/diagrams/lib/diagrams.js:2:22)
    at /packages/diagrams/lib/diagrams.js:269:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
```

### Commands

```
```

### Non-Core Packages

```
atom-material-ui 2.1.3 
atom-vagrant-manager 1.0.4 
diagrams 0.30.0 
language-jenkinsfile 0.1.1 
linter-vagrant-validate 1.1.1 
```

**Comment by Francois-Laberge-Bose** [comment]
Hmmmm. I have no idea what's going on here. I don't have time in the foreseeable future to look into this unfortunately. Unless space-pen was removed from Atom, I have no other ideas.

**Comment by Francois-Laberge-Bose** [comment]
Never mind, just checked, this package should include space-pen as seen in the [package.json](https://github.com/francoislaberge/atom-diagrams/blob/34070a82e9076c30d1eb68aec881a9879f07db44/package.json#L14)

**Comment by rantoniuk** [comment]
Well, I guess the problem is that package doesn't show up at all: https://atom.io/packages/search?q=space-pen

**Comment by Francois-Laberge-Bose** [comment]
It's hosted on NPM https://www.npmjs.com/package/space-pen
