### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by alx-ef** [francoislaberge/atom-diagrams#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [diagrams](https://github.com/francoislaberge/atom-diagrams) package 0.26.4

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\efremov_a\.atom\packages\diagrams\lib\diagrams.js:108

TypeError: Cannot read property 'length' of undefined
    at markError (/packages/diagrams/lib/diagrams.js:108:59)
    at err (/packages/diagrams/lib/diagrams.js:148:17)
    at exec (/packages/diagrams/node_modules/throttle-debounce/throttle.js:48:13)
```

### Commands

```
     -0:41.9.0 editor:select-to-end-of-word (input.hidden-input)
 30x -0:34.4.0 core:move-left (input.hidden-input)
  2x -0:30.2.0 core:move-right (input.hidden-input)
     -0:28.4.0 core:move-down (input.hidden-input)
     -0:26.9.0 core:move-up (input.hidden-input)
     -0:25.4.0 core:move-down (input.hidden-input)
  3x -0:25 core:delete (input.hidden-input)
     -0:24 editor:select-to-end-of-word (input.hidden-input)
     -0:22.9.0 core:cut (input.hidden-input)
     -0:22.7.0 editor:move-to-first-character-of-line (input.hidden-input)
     -0:22.2.0 core:paste (input.hidden-input)
     -0:21 editor:move-to-first-character-of-line (input.hidden-input)
     -0:20.6.0 core:backspace (input.hidden-input)
  6x -0:19.8.0 core:move-right (input.hidden-input)
  2x -0:16.8.0 core:backspace (input.hidden-input)
     -0:14.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
diagrams 0.26.4 
tasks 2.6.6 
```

**Comment by seflless** [comment]
@alef-ru Are you still having this issue?

**Comment by alx-ef** [comment]
I cannot check it now
